import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { EXTENSION_ID, GENERATED_MARKER, VERSION } from '../constants.js';
import {
  OMQ_SKILL_CATALOG,
  renderQwenCommandAdapterBody,
  renderQwenSkillAdapterBody,
} from './workflow-skill-catalog.js';

export interface QwenExtensionManifest {
  name: string;
  version: string;
  contextFileName: string;
  commands: string;
  skills: string;
  agents: string;
  mcpServers: Record<string, { command: string; args: string[] }>;
  settings?: unknown[];
}

export function makeExtensionManifest(): QwenExtensionManifest {
  return {
    name: EXTENSION_ID,
    version: VERSION,
    contextFileName: 'QWEN.md',
    commands: 'commands',
    skills: 'skills',
    agents: 'agents',
    mcpServers: {
      omq_state: { command: 'omq', args: ['mcp-serve', 'state'] },
      omq_memory: { command: 'omq', args: ['mcp-serve', 'memory'] },
    },
    settings: [],
  };
}

function mdHeader(path: string): string {
  return `<!-- ${GENERATED_MARKER}: ${path}. Re-run omq setup to refresh. -->\n`;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function skill(name: string, description: string, body: string): string {
  return `${mdHeader(`skills/${name}/SKILL.md`)}---\nname: ${name}\ndescription: ${yamlString(description)}\n---\n\n${body.trim()}\n`;
}

function command(name: string, body: string): string {
  return `${mdHeader(`commands/${name}.md`)}# /${name}\n\n${body.trim()}\n`;
}

function agent(name: string, description: string, body: string): string {
  return `${mdHeader(`agents/${name}.md`)}---\nname: ${name}\ndescription: ${description}\n---\n\n${body.trim()}\n`;
}

function packageRoot(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
}

function stripFrontmatter(markdown: string): string {
  if (!markdown.startsWith('---')) return markdown.trim();
  const end = markdown.indexOf('\n---', 3);
  if (end === -1) return markdown.trim();
  return markdown.slice(end + '\n---'.length).trim();
}

function readPackagedWorkflowSkillBody(name: string): string | undefined {
  const skillPath = path.join(packageRoot(), 'skills', 'workflows', name, 'SKILL.md');
  if (!existsSync(skillPath)) return undefined;
  return stripFrontmatter(readFileSync(skillPath, 'utf8'));
}

function renderSkillBody(name: string, adapterBody: string): string {
  const original = readPackagedWorkflowSkillBody(name);
  if (!original) return adapterBody;
  return `${adapterBody.trim()}\n\n---\n\n# Packaged workflow skill body\n\nThe section below is packaged from the corresponding packaged workflow skill and adapted by the OMQ contract above. Follow it where it is compatible with Qwen Code; when it references non-Qwen surfaces, use the Qwen/OMQ equivalent and state any remaining parity gap.\n\n${original}`;
}

export function renderExtensionFiles(): Record<string, string> {
  const manifest = makeExtensionManifest();
  const files: Record<string, string> = {
    'qwen-extension.json': `${JSON.stringify(manifest, null, 2)}\n`,
    'QWEN.md': `${mdHeader('QWEN.md')}# oh-my-qwen runtime contract\n\nThis Qwen extension is generated by \`omq setup\`. It provides workflow commands, skills, agents, and hooks backed by the standalone \`oh-my-qwen\` CLI.\n\n## Rules\n\n- Treat Qwen Code as the execution engine; do not modify or fork \`qwen-code\`.\n- Store durable artifacts under \`.omq/\`.\n- Prefer \`/ralplan\` for consensus planning, \`/deep-interview\` for clarification, \`/goal\` for durable ledgers, and \`/team\` for external-process team orchestration.\n- All packaged workflow skill names are present as Qwen skill adapters. Native OMQ implementations should be used when available; otherwise preserve the workflow intent and state any non-Qwen gap explicitly.\n- Use \`omq launch\` or plain \`omq\` for interactive Qwen sessions. Use \`--tmux\`, \`--direct\`, or \`OMQ_LAUNCH_POLICY\` when the default launch policy is not desired.\n- Hook-provided context is advisory unless a hook returns a blocking decision.\n`,
    'agents/planner.md': agent('planner', 'Creates implementation-ready plans and tradeoff summaries', 'Produce right-sized plans with acceptance criteria and verification steps. Be explicit about assumptions and unknowns.'),
    'agents/architect.md': agent('architect', 'Reviews architecture, boundaries, and long-horizon tradeoffs', 'Steelman the strongest alternative, identify real tradeoff tensions, and approve only when the design is maintainable.'),
    'agents/critic.md': agent('critic', 'Adversarial quality gate for plans and deliverables', 'Check consistency, testability, edge cases, reversible operations, and evidence adequacy. Return APPROVE, ITERATE, or REJECT.'),
    'agents/executor.md': agent('executor', 'Implements bounded code changes with local verification', 'Respect assigned write scope. Do not revert others. Return changed files and validation evidence.'),
    'agents/verifier.md': agent('verifier', 'Validates completion claims against acceptance criteria', 'Prefer concrete commands/artifacts over vibes. Distinguish evidence from inference.'),
    'agents/researcher.md': agent('researcher', 'Gathers official/upstream evidence for external behavior', 'Use official docs and local upstream references first. Summarize version-specific findings and cite paths/URLs.'),
  };

  for (const entry of OMQ_SKILL_CATALOG) {
    files[`commands/${entry.name}.md`] = command(entry.name, renderQwenCommandAdapterBody(entry));
    files[`skills/${entry.name}/SKILL.md`] = skill(entry.name, entry.description, renderSkillBody(entry.name, renderQwenSkillAdapterBody(entry)));
  }

  return files;
}
