import { EXTENSION_ID, GENERATED_MARKER, VERSION } from '../constants.js';

export interface QwenExtensionManifest {
  name: string;
  version: string;
  contextFileName: string;
  commands: string;
  skills: string;
  agents: string;
  mcpServers: Record<string, { command: string; args: string[] }>;
  settings?: unknown[];
}

export function makeExtensionManifest(): QwenExtensionManifest {
  return {
    name: EXTENSION_ID,
    version: VERSION,
    contextFileName: 'QWEN.md',
    commands: 'commands',
    skills: 'skills',
    agents: 'agents',
    mcpServers: {
      omq_state: { command: 'omq', args: ['mcp-serve', 'state'] },
      omq_memory: { command: 'omq', args: ['mcp-serve', 'memory'] },
    },
    settings: [],
  };
}

function mdHeader(path: string): string {
  return `<!-- ${GENERATED_MARKER}: ${path}. Re-run omq setup to refresh. -->\n`;
}

function skill(name: string, description: string, body: string): string {
  return `${mdHeader(`skills/${name}/SKILL.md`)}---\nname: ${name}\ndescription: ${description}\n---\n\n${body.trim()}\n`;
}

function command(name: string, body: string): string {
  return `${mdHeader(`commands/${name}.md`)}# /${name}\n\n${body.trim()}\n`;
}

function agent(name: string, description: string, body: string): string {
  return `${mdHeader(`agents/${name}.md`)}---\nname: ${name}\ndescription: ${description}\n---\n\n${body.trim()}\n`;
}

export function renderExtensionFiles(): Record<string, string> {
  const manifest = makeExtensionManifest();
  return {
    'qwen-extension.json': `${JSON.stringify(manifest, null, 2)}\n`,
    'QWEN.md': `${mdHeader('QWEN.md')}# oh-my-qwen runtime contract\n\nThis Qwen extension is generated by \`omq setup\`. It provides workflow commands, skills, agents, and hooks backed by the standalone \`oh-my-qwen\` CLI.\n\n## Rules\n\n- Treat Qwen Code as the execution engine; do not modify or fork \`qwen-code\`.\n- Store durable artifacts under \`.omq/\`.\n- Prefer \`/ralplan\` for consensus planning, \`/deep-interview\` for clarification, \`/goal\` for durable ledgers, and \`/team\` for external-process team orchestration.\n- Hook-provided context is advisory unless a hook returns a blocking decision.\n`,
    'commands/ralplan.md': command('ralplan', 'Create a consensus-ready plan. Write PRD/test-spec artifacts under `.omq/plans`, review architecture and critique sequentially, and do not start implementation until the plan is approved.'),
    'commands/deep-interview.md': command('deep-interview', 'Run a concise Socratic clarification pass. Capture task statement, desired outcome, constraints, unknowns, and acceptance criteria under `.omq/context`.'),
    'commands/goal.md': command('goal', 'Create or advance a durable `.omq/goals` ledger. Track objective, checkpoints, validation evidence, and terminal outcome.'),
    'commands/team.md': command('team', 'Plan external Qwen worker lanes with tmux and git worktrees. Use Qwen subagents for read-only/review lanes only unless isolation is explicit.'),
    'skills/ralplan/SKILL.md': skill('ralplan', 'Consensus planning workflow for Qwen Code', 'Use Planner → Architect → Critic review order. Include principles, decision drivers, alternatives, acceptance criteria, and concrete verification. Persist outputs under `.omq/plans` and `.omq/reviews`.'),
    'skills/deep-interview/SKILL.md': skill('deep-interview', 'Clarify ambiguous tasks before execution', 'Ask the smallest set of high-impact questions needed to remove ambiguity. If the user has already provided enough detail, write the context snapshot and proceed.'),
    'skills/goal/SKILL.md': skill('goal', 'Durable goal ledger workflow', 'Represent work as checkpoints with proof commands/artifacts. Terminal statuses are finished, blocked, failed, or askuserQuestion.'),
    'skills/team/SKILL.md': skill('team', 'External-process team orchestration', 'Use independent write scopes, tmux panes, and git worktrees for write-heavy parallel work. Collect evidence back into `.omq/team`.'),
    'agents/planner.md': agent('planner', 'Creates implementation-ready plans and tradeoff summaries', 'Produce right-sized plans with acceptance criteria and verification steps. Be explicit about assumptions and unknowns.'),
    'agents/architect.md': agent('architect', 'Reviews architecture, boundaries, and long-horizon tradeoffs', 'Steelman the strongest alternative, identify real tradeoff tensions, and approve only when the design is maintainable.'),
    'agents/critic.md': agent('critic', 'Adversarial quality gate for plans and deliverables', 'Check consistency, testability, edge cases, reversible operations, and evidence adequacy. Return APPROVE, ITERATE, or REJECT.'),
    'agents/executor.md': agent('executor', 'Implements bounded code changes with local verification', 'Respect assigned write scope. Do not revert others. Return changed files and validation evidence.'),
    'agents/verifier.md': agent('verifier', 'Validates completion claims against acceptance criteria', 'Prefer concrete commands/artifacts over vibes. Distinguish evidence from inference.'),
    'agents/researcher.md': agent('researcher', 'Gathers official/upstream evidence for external behavior', 'Use official docs and local upstream references first. Summarize version-specific findings and cite paths/URLs.'),
  };
}
