import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { mergeOmqHooks, removeOmqHooks, removeOmqMcpServers, upsertSettingsHooks } from '../settings.js';

test('settings merge preserves user hooks and upserts OMQ-owned hooks', () => {
  const input = {
    disableAllHooks: true,
    custom: { keep: true },
    hooks: {
      PreToolUse: [
        { matcher: 'Bash', hooks: [{ type: 'command', command: 'echo user' }] },
        { matcher: '.*', hooks: [{ type: 'command', command: 'node old.js --omq-owned=oh-my-qwen' }] },
      ],
    },
  };
  const result = mergeOmqHooks(input, 'node hook.js --omq-owned=oh-my-qwen', {
    omq_state: { command: 'node', args: ['dist/mcp/state-server.js'], description: 'Generated by oh-my-qwen: test' },
    omq_memory: { command: 'node', args: ['dist/mcp/memory-server.js'], description: 'Generated by oh-my-qwen: test' },
    omq_wiki: { command: 'node', args: ['dist/mcp/wiki-server.js'], description: 'Generated by oh-my-qwen: test' },
  });
  assert.equal(result.disabled, true);
  assert.equal(result.removedOwnedHooks, 1);
  assert.deepEqual(result.installedMcpServers.sort(), ['omq_memory', 'omq_state', 'omq_wiki']);
  assert.equal((result.settings.custom as { keep: boolean }).keep, true);
  const pre = (result.settings.hooks as Record<string, Array<{ hooks: Array<{ command: string }> }>>).PreToolUse;
  assert.equal(pre.some((group) => group.hooks.some((hook) => hook.command === 'echo user')), true);
  assert.equal(pre.filter((group) => group.hooks.some((hook) => hook.command.includes('--omq-owned=oh-my-qwen'))).length, 1);
});

test('MCP merge skips non-owned server keys and removes only owned MCP servers', () => {
  const input = {
    mcpServers: {
      omq_state: { command: 'custom-state' },
      omq_memory: { command: 'node', args: ['omq.js', 'mcp-serve', 'memory'], description: 'Generated by oh-my-qwen: memory' },
      omq_wiki: { command: 'node', args: ['dist/mcp/wiki-server.js'], description: 'Generated by oh-my-qwen: wiki' },
      user_server: { command: 'user' },
    },
  };
  const merged = mergeOmqHooks(input, 'node hook.js --omq-owned=oh-my-qwen', {
    omq_state: { command: 'node', args: ['dist/mcp/state-server.js'], description: 'Generated by oh-my-qwen: state' },
    omq_memory: { command: 'node', args: ['dist/mcp/memory-server.js'], description: 'Generated by oh-my-qwen: memory' },
    omq_wiki: { command: 'node', args: ['dist/mcp/wiki-server.js'], description: 'Generated by oh-my-qwen: wiki' },
  });
  assert.deepEqual(merged.skippedMcpServers, ['omq_state']);
  const servers = merged.settings.mcpServers as Record<string, { command: string }>;
  assert.equal(servers.omq_state.command, 'custom-state');
  assert.equal(servers.omq_memory.command, 'node');

  const removed = removeOmqMcpServers(merged.settings);
  const kept = removed.settings.mcpServers as Record<string, { command: string }>;
  assert.equal(removed.removed, 2);
  assert.equal(kept.omq_state.command, 'custom-state');
  assert.equal(kept.user_server.command, 'user');
  assert.equal('omq_memory' in kept, false);
  assert.equal('omq_wiki' in kept, false);
});

test('removeSettingsHooks removes only OMQ-owned hooks', () => {
  const result = removeOmqHooks({ hooks: { Stop: [{ hooks: [{ type: 'command', command: 'user' }, { type: 'command', command: 'omq --omq-owned=oh-my-qwen' }] }] } });
  assert.equal(result.removed, 1);
  const stop = (result.settings.hooks as Record<string, Array<{ hooks: Array<{ command: string }> }>>).Stop;
  assert.deepEqual(stop[0].hooks.map((hook) => hook.command), ['user']);
});

test('upsertSettingsHooks creates backups and respects QWEN_HOME', async () => {
  const home = await mkdtemp(path.join(os.tmpdir(), 'omq-home-'));
  const cwd = await mkdtemp(path.join(os.tmpdir(), 'omq-cwd-'));
  const settingsPath = path.join(home, 'settings.json');
  await writeFile(settingsPath, JSON.stringify({ hooks: { Stop: [{ hooks: [{ type: 'command', command: 'user' }] }] } }));
  const summary = await upsertSettingsHooks({ scope: 'user', cwd, env: { ...process.env, QWEN_HOME: home } }, 'node hook.js --omq-owned=oh-my-qwen');
  assert.equal(summary.settingsPath, settingsPath);
  assert.ok(summary.backupPath);
  const written = JSON.parse(await readFile(settingsPath, 'utf8')) as { hooks: Record<string, unknown>; mcpServers: Record<string, unknown> };
  assert.ok(written.hooks.UserPromptSubmit);
  assert.ok(written.hooks.Stop);
  assert.ok(written.mcpServers.omq_state);
  assert.ok(written.mcpServers.omq_memory);
  assert.ok(written.mcpServers.omq_wiki);
});
