export const PACKAGE_NAME = 'oh-my-qwen';
export const EXTENSION_ID = 'oh-my-qwen';
export const VERSION = '0.1.0';
export const STATE_DIR = '.omq';
export const OMQ_OWNER_ARG = '--omq-owned=oh-my-qwen';
export const GENERATED_MARKER = 'Generated by oh-my-qwen';

export const QWEN_HOOK_EVENTS = [
  'SessionStart',
  'UserPromptSubmit',
  'PreToolUse',
  'PostToolUse',
  'PostToolUseFailure',
  'Stop',
  'SubagentStart',
  'SubagentStop',
  'SessionEnd',
  'PreCompact',
  'PostCompact',
] as const;

export type QwenHookEventName = (typeof QWEN_HOOK_EVENTS)[number];

export const TERMINAL_OUTCOMES = new Set([
  'finished',
  'complete',
  'completed',
  'blocked',
  'failed',
  'cancelled',
  'canceled',
  'askuserQuestion',
  'ask_user_question',
]);
